apiVersion: v1
kind: Service
metadata:
    name: jonathankayumbopythonmicroservice
spec:
    type: LoadBalancer
    ports:
    - port: 9090 
    selector:
        app: jonathankayumbopythonmicroservice